### ISSUE TITLE
Change maintainer?

### ISSUE THREAD

**Issue by ghost** [GaloisInc/mime#13]
Should DavidCTurner become the maintainer now?

**Comment by ghost** [comment]
ping @davidcturner @dato @yurael Let us know if anybody has interest in become the maintainer? MackeyRMS might be able to finish implementing a full regression test suite to facilitate anyone who does express interest.

**Comment by ghost** [comment]
ping @davecturner

**Comment by dato** [comment]
(Not interested, apologies.)

**Comment by DaveCTurner** [comment]
Sorry, I don't have the bandwidth for this right now.

**Comment by ghost** [comment]
Starting unit tests for now. We'll see how much this aligns with our other work.
